### ISSUE TITLE
Client should remove uri args when saving chunks

### ISSUE THREAD

**Issue by jbochi** [globocom/hlsclient#12]
For instance, when we try to consume a wowza stream with our client, it saves the files with a `?wowzasessionid=99999` suffix.

**Comment by hltbra** [comment]
I think it is solved by the absolute_uri approach. Check commit https://github.com/globocom/hlsclient/commit/f42545b3dd996fff5219ebbf61bcd199b3e88db8

Anyway, it would be nice to have a test with this behavior.

**Comment by hltbra** [comment]
Oh, and m3u8 commits:

https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L184

https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L330
