### ISSUE TITLE
capturing a single HLS source with two hls clients in parallel.

### ISSUE THREAD

**Issue by skoppisetty** [globocom/hlsclient#46]
Does this hls client support parallel capturing of a single live stream ?? 

I need to (simple stress test) simulate two clients capturing a live HLS stream and store them with different names, so that i can test. 

Thanks,
Suresh

**Comment by hltbra** [comment]
I think it is not possible, but it is easy to start 2 `hlsclient`s, each one with a different config file (.ini).

**Comment by skoppisetty** [comment]
can i pass the config file using parameters ?

**Comment by hltbra** [comment]
`HLSCLIENT_CONFIG=/path/to/config.ini python -m hlsclient`

**Comment by skoppisetty** [comment]
HLSCLIENT_CONFIG=/path/to/config_1.ini python -m hlsclient
HLSCLIENT_CONFIG=/path/to/config_2.ini python -m hlsclient

should work right ? should i need to change the lock folder also or just the destination folder change would do ?

**Comment by hltbra** [comment]
Change the lock and destination directories to avoid headaches and bug hunting.

**Comment by skoppisetty** [comment]
Thanks it worked :)
